# Generated by Django 5.0.7 on 2024-10-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='account_profile',
        ),
    ]
