# Generated by Django 5.0.7 on 2024-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(),
        ),
    ]
